import { MantineProvider } from '@mantine/core';
import '@mantine/core/styles.layer.css';
import type { Metadata } from 'next';

import Header from './components/header/Header';
import './globals.css';
import { theme } from './theme/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <Header />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
