import { MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import { cookies } from 'next/headers';
import { TRPCReactProvider } from '~/trpc/react';

import { fetchSettingsData } from '~/server/sanity/sanity.utils';
import '~/styles/globals.css';
import Footer from './_components/footer/Footer';
import { theme } from './theme/theme';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const settingsData = await fetchSettingsData();
  const { footer } = settingsData;
  return (
    <html lang='en'>
      <body>
        <TRPCReactProvider cookies={cookies().toString()}>
          <MantineProvider theme={theme}>
            {children}
            <Footer footer={footer} />
          </MantineProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
