import { Container, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import { cookies } from 'next/headers';
import { fetchSettingsData } from '~/server/sanity/sanity.utils';
import { TRPCReactProvider } from '~/trpc/react';

import '~/styles/globals.css';
import Header from './_components/header/Header';
import { theme } from './theme/theme';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const settingsData = await fetchSettingsData();
  const { header } = settingsData;

  return (
    <html lang='en'>
      <body>
        <TRPCReactProvider cookies={cookies().toString()}>
          <MantineProvider theme={theme}>
            <Header header={header} />
            <Container style={{ marginTop: '112px' }}>{children}</Container>
          </MantineProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
